### PR TITLE
Fractal dimension index 

### PR DESCRIPTION
**Pull request by mahdibp7**
Please review the code and test it using the test file

### CODE REVIEW

**Comment by vd1371** [comment]
1- based on the website you wrote in the code: hig_max and low_max must be the highest and lowest values of CLOSE and not HIGH and LOW, but...
2- based on the mt4 code, there is an option to choose among Open, High, Low, Close, please also add this option. Similar to SMA and EMA
3- it returns a numpy array but we need a panda series correct index so we could concatenate these values in the future

**Comment by vd1371** [comment]
I forgot sth else

See if you can use rolling instead of for i in range (self......
I think this code should be too slow. Rolling is a game-changing method

**Comment by vd1371** [comment]
[Volume - Fractal Dimension](https://trello.com/c/isW4F9a8/40-volume-fractal-dimension)

**Comment by vd1371** [comment]
[Volume - Fractal Dimension](https://trello.com/c/isW4F9a8/40-volume-fractal-dimension)

**Comment by mahdibp7** [comment]
I have addressed the comments. Please review the code again. Thanks

**Pull request merged**
